version: "3.9"

services:
  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    ports:
      - "32768:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - keycloak-postgres
    command:
      - start-dev

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: yasha
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin-cloack:
    container_name: pgadmin-cloack
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-cloack:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - keycloak-postgres
    restart: unless-stopped


volumes:
  keycloak-postgres-data:
    driver: local
  pgadmin-cloack:
    driver: local
  postgres:
    driver: local
  pgadmin:
    driver: local

networks:
  keycloak-postgres:
  postgres:

