server:
  port: 8083


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: http://localhost:8081/messages
          predicates:
            - Path=/messages/**





